remote_theme: pages-themes/modernist@v0.2.0
title: /r/Steroids Wiki
description: TODO
markdown: GFM
highlighter: rouge
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - INDEX.md
  - README.md

